name: climulatorscore
channels:
  - conda-forge
dependencies:
  - scikit-learn>=1.3.2
  - numpy>=1.24.2
  - scipy>=1.10.0
  - matplotlib>=3.6.3
  - netcdf4>=1.6.2
  - pytest>=7.2.1
  - pyyaml>=6.0.2
  - cartopy>=0.24.0
  - pandas>=2.2.3 
  - pillow>=11.1.0  
  - python>=3.9
