base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna"

variables: 
  - "mrsol"
  - "pr"

experiment: "test_SRGAN"

data_path:
  # pr
  HCLIM 3km mrsol: "${base_dir}/cropped/ECMWF-ERAINT/3km/6hr/mrsol/mrsol_3km_6hr_200001010000-200912311800.nc"
  HCLIM 3km pr: "${base_dir}/cropped/ECMWF-ERAINT/3km/6hr/pr/pr_3km_6hr_200001010300-200912312100.nc"
  HCLIM 12km mrsol: "${base_dir}/cropped/ECMWF-ERAINT/12km/6hr/mrsol/mrsol_12km_6hr_200001010000-200912311800.nc"
  HCLIM 12km pr: "${base_dir}/cropped/ECMWF-ERAINT/12km/6hr/pr/pr_12km_6hr_200001010300-200912312100.nc"
  SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_mrsol_with_mrsol_val0.1_atos/predictant_ypred.nc"
  SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_with_pr_val0.1_atos/predictant_ypred.nc"

  #HCLIM 3km: "${base_dir}/cropped/ECMWF-ERAINT/3km/6hr/${variables}/${variables}_3km_6hr_200001010300-200912312100.nc"
  #HCLIM 12km: "${base_dir}/cropped/ECMWF-ERAINT/12km/6hr/${variables}/${variables}_12km_6hr_200001010300-200912312100.nc"
  #SRGAN 3km val0.1 atos no pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_no_${variables}_val0.1_atos/predictant_ypred.nc"
  #SRGAN 3km val0.1 atos with pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_with_${variables}_val0.1_atos/predictant_ypred.nc"
  #SRGAN 3km Freja: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_no_${variables}/predictant_ypred.nc"
  #SRGAN 3km val0.1 Freja: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_no_${variables}_val0.1_Freja/predictant_ypred.nc"
  #SRGAN 3km with pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_no_${variables}/predictant_ypred.nc"
  #CNN 3km: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_${variables}_2009.nc"

  # mrsol
  #HCLIM 3km: "${base_dir}/cropped/3km/6hr/${variables}/${variables}_3km_6hr_200001010000-200912311800.nc"
  ##HCLIM 12km: "${base_dir}/cropped/12km/6hr/${variables}/${variables}_12km_6hr_200001010000-200912311800.nc"
  #SRGAN 3km: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}/predictant_ypred.nc"
  #CNN 3km: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_${variables}_2009.nc"

output_dir: "${base_dir}/statistic_figs" 

statistics:
  #- rmse
  - cpl_corr
  #- correlation
  #- mean_bias
  #- variance_ratio
  #- wasserstein
  #- percentile_99
  #- mean_value
  #- abs_value

min_max_scale:
  #'rmse': 
  ##'correlation': [0.88, 1.00]
  'cpl_corr':
  #'correlation':
  #'mean_bias':
  #'variance_ratio':
  #'wasserstein':
  #'percentile_99': 
  #'mean_value':
  #'abs_value':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

