base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna"

variables: "tas"

experiment: "test_algorithm"

data_path:
  HCLIM 3km: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_no_pr/predictant_ytest.nc"
  HCLIM 12km: "${base_dir}/SG/SRGAN_OUT/EPOCH1_tas_with_tas/predictor.nc"
  SRGAN 3km: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_no_pr/predictant_ypred.nc"

output_dir: "${base_dir}/statistic_figs" 

statistics:
  - rmse
  - correlation
  - mean_bias
  - variance_ratio
  - wasserstein
  - percentile_99
  - mean_value
  - abs_value

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0

