base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna"
#GCM: "ICHEC-EC-EARTH_HIST"
#FIRST_YEAR: "1995"
#LAST_YEAR: "2005"
GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "pr"

#experiment: "SRGAN_TOROGSENS_ERAI_SCSTD_GPU_paper"
#experiment: "SRGAN_TOROGSENS_ERAI_test2y_2009_paper"
#experiment: "SRGAN_WPWOROG_CNN_ERAI_SCSTD_GPU_paper"
#experiment: "SRGAN_NPNOROG_CNN_ERAI_SCSTD_GPU_paper"
#experiment: "SRGAN_NPNOROG_CNN_ERAI_test2y_2009"
#experiment: "SRGAN_WPWOROG_CNN_ERAI_test2y_2009"
#experiment: "SRGAN_WPWOROG_CNN_ERAI_PSD_paper"
experiment: "SRGAN_NOROG_CNN_ERAI_test2y_2009_PSD"
#experiment: "CNN_WP_NP_ERAI_SCSTD_GPU_paper"
MLEXP: ''
CNNEXP: ''
SRGANEXP: ''

FREQUENCY: '6hr'

data_path:
  # pr
  HCLIM 3km pr: "${base_dir}/cropped/ECMWF-ERAINT/3km/6hr/pr/pr_3km_6hr_200001010300-200912312100.nc"
  HCLIM 12km pr: "${base_dir}/cropped/ECMWF-ERAINT/12km/6hr/pr/pr_12km_6hr_200001010300-200912312100.nc"
  CNN 3km pr: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_pr_2009.nc"
  # With P With OROG
  #SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_wp_worog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  # With P With OROG, train 2000-2002, 2004-2008, test 2003 & 2009
  ###SRGAN 3km pr:  "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsmpo_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  #SRGAN 3km pr:  "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsmpo_v2_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  ###SRGAN 3km pr:  "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsmpo_tile_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  # No P No OROG
  ###SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_np_norog_gpufix_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  #SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsm_corrv2_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc" #PSD
  SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsm_corr_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc" #BIAS, RMSE, P99
  ###SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsm_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"

  # CNN with pr as input
  #CNN_NPNOROG 3km pr: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_pr_2009.nc"
  #CNN_WPNOROG 3km pr: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/AIES_revision_aug2026/PR_ERAINT/simple_cnn_prediction_withP.nc"

  ####SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_worog_wp_bs60_ERAI_alvis/predictant_ypred_1.nc"
  ###SRGAN 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_wp_worog_gpufix_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  # No P No OROG
  #SRGAN_NPNOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_np_norog_gpufix_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  #SRGAN_NPWOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_np_worog_gpufix_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  #SRGAN_WPNOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_wp_norog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  #SRGAN_WPWOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_wp_worog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  # No P No OROG, 2003_2009
  ##SRGAN_NPNOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsm_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  #SRGAN_NPNOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsm_corrv2_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  #SRGAN_NPWOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsmo_corr_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  #SRGAN_WPNOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsmp_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  #SRGAN_WPWOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/ARRHENIUS/EPOCH100_pr_wsmpo_ERAI_2003_2009_arrhenius/predictant_ypred_2.nc"
  # not used
  ##SRGANNPNOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_np_norog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  ##SRGANWPWOROG 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_scale_time_stdscaler_wp_worog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"

reference_experiment:
  HCLIM_HI 3km:
  HCLIM_HI 12km: 'HCLIM 3km'
  HCLIM 12km: 'HCLIM 3km'
  CNN 3km: 'HCLIM 3km'
  SRGAN 3km: 'HCLIM 3km'
  SRGAN_NPNOROG 3km: 'HCLIM 3km'
  SRGAN_NPWOROG 3km: 'HCLIM 3km'
  SRGAN_WPNOROG 3km: 'HCLIM 3km'
  CNN_NPNOROG 3km: 'HCLIM 3km'
  CNN_WPNOROG 3km: 'HCLIM 3km'

time_range:
  HCLIM 12km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'pr': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  HCLIM 3km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
             'pr': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
             'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  SRGAN 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  SRGAN_WPWOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  SRGAN_NPNOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  SRGAN_NPWOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  SRGAN_WPNOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  CNN 3km: {'mrsol': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'pr': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  CNN_NPNOROG 3km: {'mrsol': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'pr': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  CNN_WPNOROG 3km: {'mrsol': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'pr': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'target': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6} }
  #target: {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}

#output_dir: "${base_dir}/statistic_figs/1var/paper" 
#output_dir: "${base_dir}/statistic_figs/1var/paper_revision1/2009/SENS/" 
#output_dir: "${base_dir}/statistic_figs/1var/paper_revision1/2009/SENS_2y/" 
#output_dir: "${base_dir}/statistic_figs/1var/paper_revision1/2009/CNN_NT/" 
#output_dir: "${base_dir}/statistic_figs/1var/paper_revision1/2009/SRGAN_NPNOROG/" 
#output_dir: "${base_dir}/statistic_figs/1var/paper_revision1/2009/TEST_2003_2009/" 
output_dir: "${base_dir}/statistic_figs/psd/" 

statistics:
  #- rmse
  #- cpl_corr
  #- correlation
  #- mean_bias
  #- percentile_99_bias
  #- variance_ratio
  #- wasserstein
  #- percentile_99
  #- mean_value
  #- abs_value
  #- std
  - psd

min_max_scale:
  #'rmse': 
  #'correlation': [0.88, 1.00]
  #'cpl_corr':
  #'mean_bias': [-4, 4] 
  #'percentile_99_bias': [-50, 50] 
  #'variance_ratio':
  #'wasserstein':
  #'percentile_99': [0, 120] 
  #'mean_value': [0, 15]
  #'abs_value':
  #'std':
  'psd':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  #'nrows_def': 1
  #'ncols_def': 4
  #'figsize_def': [50,10]
  'nrows_def': 2
  'ncols_def': 2
  'figsize_def': [22,15]
  #'nrows_def': 3
  #'ncols_def': 1
  #'figsize_def': [16,30]
  #'nrows_def': 5
  #'ncols_def': 1
  #'figsize_def': [13,40]
  'fontsize_def': 26
  'nlevels_def': 11
  #'extend_def': 'max'
  'extend_def': 'both'
